#Server Configuration
server:
  port: 8080

#Database Configuration
spring:
  datasource:
    database: hexaware
    table1: department
    table2: employee
#    database: jails
#    table1: jail
#    table2: prisoner
#    database: world
#    table1: country
#    table2: citizen
#    database: JailDepartmentOfTheWorld
    url: jdbc:mysql://localhost:3306/${spring.datasource.database}
    username: root
    password: Password123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #ActiveMQ Configuration
  activemq:
    broker-url: tcp://localhost:61616
    username: admin
    password: admin
    packages:
      trust-all: true

  #MongoDB configurations
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.datasource.database}
#      uri: mongodb+srv://${spring.datasource.username}:${spring.datasource.password}@cluster0.m9onumq.mongodb.net/${spring.datasource.database}
      database: ${spring.datasource.database}

#Active profile
  profiles:
    active: development