#Server Configuration
server:
  port: 8080

#Database Configuration
spring:
  datasource:
    database: Hexaware
    table1: department
    table2: employee
    #database: jails
    #table1: jail
    #table2: prisoner
    url: jdbc:mysql://localhost:3306/${spring.datasource.database}
    username: root
    password: Password123
    driver-class-name: com.mysql.cj.jdbc.Driver

  #ActiveMQ Configuration
  activemq:
    broker-url: tcp://localhost:61616
    username: admin
    password: admin
    packages:
      trust-all: true

  #MongoDB configurations
  data:
    mongodb:
      uri: mongodb://localhost:27017/${spring.datasource.database}
      database: ${spring.datasource.database}

#Active profile
  profiles:
    active: development