#Server Configuration
server:
  port: 8080

#Database Configuration
spring:
  datasource:
    database: hexaware
    table1: department
    table2: employee
    #database: jails
    #table1: jail
    #table2: prisoner
    url: jdbc:mysql://localhost:3306/${spring.datasource.database}
    username: root
    password: Password123
    driver-class-name: com.mysql.cj.jdbc.Driver

#Active profile
  profiles:
    active: development